### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by orgads** [googleapis/gapic-generator-typescript#1012]
Thanks for stopping by to let us know something could be better!

#### Environment details
Docker image

#### Steps to reproduce

  1. Run `docker run --rm --user $UID -v $PWD:/in -v $PWD/proto:/out gcr.io/gapic-images/gapic-generator-typescript:latest`

Looks like gapic-generator is missing a module named 'generator'.

```
gapic-generator-typescript: https://github.com/googleapis/gapic-generator-typescript
Latest commit: 
commit 527b5af5cc9b92900dd5f05a0f485dd07ed4fbdb
Author: Alice <65933803+alicejli@users.noreply.github.com>
Date:   Wed Aug 11 17:59:42 2021 -0700

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module './generator'
Require stack:
- /usr/local/lib/node_modules/@google-cloud/gapic-generator/build/typescript/src/protoc-plugin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/gapic-generator/build/typescript/src/protoc-plugin.js:18:21)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@google-cloud/gapic-generator/build/typescript/src/protoc-plugin.js'
  ]
}
--typescript_gapic_out: protoc-gen-typescript_gapic: Plugin failed with status code 1.
child_process.js:642
    throw err;
    ^

Error: Command failed: protoc --plugin=protoc-gen-typescript_gapic=/usr/local/lib/node_modules/@google-cloud/gapic-generator/build/typescript/src/protoc-plugin.js --typescript_gapic_out=/out -I/in /in/proto/protos/synthesizer.proto -I/protos/api-common-protos-master
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/gapic-generator/build/typescript/src/gapic-generator-typescript.js:136:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18,
  stdout: null,
  stderr: null
}
```

**Comment by marcantoine-bibeau** [comment]
Any ETA on this please? Thanks!

**Comment by summer-ji-eng** [comment]
> Any ETA on this please? Thanks!

ETA in Q2 2022.

**Comment by summer-ji-eng** [comment]
@marcantoine-bibeau have you tried using bazel?

**Comment by alexander-fenster** [comment]
Finally - I made it work and updated Docker image for the generator :)
