### ISSUE TITLE
Unable to set httpTarget update mask in gRPC scheduler client

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#943]
There is an [odd issue](https://github.com/googleapis/nodejs-scheduler/issues/370) occurring, in which setting the `httpTarget` update mask on the scheduler client results in the following exception:

```
Error: 3 INVALID_ARGUMENT: Invalid mask for Job: httpTarget at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26) at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:179:52) at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141) at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181) at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78 at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Similar code in the Python gRPC client succeeds:

```python
from google.cloud import scheduler_v1beta1
from google.protobuf.field_mask_pb2 import FieldMask
 
job_id="http_job"
location="us-central1"
project="ekaramad-playground"
 
job_name=f"projects/{project}/locations/{location}/jobs/{job_id}"
 
client = scheduler_v1beta1.CloudSchedulerClient()
 
job = client.get_job(name=job_name)
print(job)
# client.update_job(job={'name': job_name, 'http_target': {'uri': 'https://www4.google.ca'}})
mask = FieldMask()
mask.FromJsonString('httpTarget')
client.update_job(job=job, update_mask=mask)
```

This makes me think the issue is potentially a problem with the generator.

CC:  @averikitsch

**Comment by summer-ji-eng** [comment]
I am able to reproduce the error on my local. The error is directly from the service with returning a metadata, has the following 3 fields.
![image](https://user-images.githubusercontent.com/6378676/128312719-c664ec95-cd64-4031-810a-a46cef1d5971.png)
I don't see any suspect error in client library or gax-nodejs. I wonder if it is possible the API service team has issue?
```
try {
 const getJobRequest = {
  name: jobName
}
  const [job] = await client.getJob(getJobRequest);
  console.log(`job: ${JSON.stringify(job)}`);
  const updateRequest = {
    job: {
      name: jobName,
      description: 'summer edit',
      httpTarget: {
        uri: url,
        httpMethod: 'POST',
        body: Buffer.from('Hello World Again'),
      },
    },
    updateMask: {
      paths: ['httpTarget'],
    },
  }
  const [response] = await client.updateJob(updateRequest);
  console.log(`Updated job: ${JSON.stringify(response)}`);
} catch (err) {
  console.log(err);
}
```
The error log:
```
Error: 3 INVALID_ARGUMENT: Invalid mask for Job: httpTarget
    at Object.callErrorFromStatus (/Users/summerji/Work/nodejs/tryScheduler/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/summerji/Work/nodejs/tryScheduler/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/Users/summerji/Work/nodejs/tryScheduler/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/Users/summerji/Work/nodejs/tryScheduler/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /Users/summerji/Work/nodejs/tryScheduler/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 3,
  details: 'Invalid mask for Job: httpTarget',
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  }
}
```

**Comment by summer-ji-eng** [comment]
The most of fields of [job](https://github.com/googleapis/nodejs-scheduler/blob/master/protos/google/cloud/scheduler/v1/job.proto#L34-L170) is able to update, except for `httpTarget`, `pubsubTarget`, `schedule`, `timezone` and some of output only field is ignored. 
According to [AIP161](https://google.aip.dev/161)"the service may choose to error with INVALID_ARGUMENT if the field is modified in input."

Will close the ticket for now. Feel free to reach out if you have further question. Thanks.
